# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TicTacToeApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TicTacToeApp
    pod 'Leanplum-iOS-SDK'

    # Uncomment for UI Editor.
     pod 'Leanplum-iOS-UIEditor'

    # Uncomment one of the following for Location Services.
    # pod 'Leanplum-iOS-Location'
     pod 'Leanplum-iOS-LocationAndBeacons'
end
